import React from 'react';
import EditableCompliancePage from '../../../components/EditableCompliancePage/EditableCompliancePage';

const AIVendorEvaluation = () => {
    const defaultTitle = "AI Vendor Evaluation Checklist";
    const defaultHtmlContent = `
        <div class="mb-4">
            <p class="text-muted">Due diligence checklist for vetting new AI tools before adoption.</p>
        </div>

        <div class="alert alert-warning mb-4">
            <i class="bi bi-exclamation-triangle-fill me-2"></i>
            <strong>Note:</strong> This page is a static template for reference.
        </div>

        <div class="policy-section mb-4">
            <h4>1. Data Privacy & Security</h4>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="dataStorage" disabled>
                <label class="form-check-label" for="dataStorage">
                    Data Storage: Does the vendor state clearly where data is stored (EU/US)? Is it encrypted at rest?
                </label>
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="trainingUse" disabled>
                <label class="form-check-label" for="trainingUse">
                    Generative AI Training: Can we opt-out of our data being used to train their public models?
                </label>
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="gdpr" disabled>
                <label class="form-check-label" for="gdpr">
                    GDPR Compliance: Do they have a DPA (Data Processing Agreement) available?
                </label>
            </div>
        </div>

        <div class="policy-section mb-4">
            <h4>2. Legal & Control</h4>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="terms" disabled>
                <label class="form-check-label" for="terms">
                    Terms of Service: Do we retain ownership of the output generated by the tool?
                </label>
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="deletion" disabled>
                <label class="form-check-label" for="deletion">
                    Data Deletion: Is there a clear process to delete our account and all associated data?
                </label>
            </div>
        </div>
    `;

    return (
                <EditableCompliancePage
            pageKey="ai_vendor_evaluation"
            defaultTitle={defaultTitle}
            defaultHtmlContent={defaultHtmlContent}
        />
            );
};

export default AIVendorEvaluation;
